[package]
name = "if_statement"
version = "0.1.0"
authors = ["phantom05 <monster2jy@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
